#!/usr/bin/env bash
# gen-index.sh — Auto-generate docs/index.md from frontmatter
# Paths are relative to docs/index.md (e.g., current/SDD.md)
set -eu

OUTPUT="docs/index.md"

# Extract first H1 title from a markdown file, stripping CR
extract_title() { grep "^# " "$1" | head -1 | sed 's/^# //' | tr -d '\r'; }
# Extract a frontmatter field value from the first 20 lines, stripping CR
extract_field() { head -20 "$1" | grep "^$2:" | sed "s/^$2: *//" | tr -d '\r'; }

cat <<'HEADER' > "$OUTPUT"
---
status: active
source_of_truth: generated
owner: ci-bot
last_verified: AUTOGENERATED
---
# Documentation Index

> Auto-generated by `scripts/ci/gen-index.sh`. Do not edit manually.
HEADER

# --- Current (Active) ---
echo -e "\n## Current (Active)\n" >> "$OUTPUT"
for f in docs/current/*.md; do
  [ -f "$f" ] || continue
  fname=$(basename "$f")
  title=$(extract_title "$f")
  sot=$(extract_field "$f" "source_of_truth")
  code_ref=$(extract_field "$f" "code_ref")

  line="- [${title:-$fname}](current/$fname)"
  [ -n "$sot" ] && line="$line — source: \`$sot\`"
  [ -n "$code_ref" ] && line="$line → \`$code_ref\`"
  echo "$line" >> "$OUTPUT"
done

# --- ADR ---
if ls docs/adr/*.md &>/dev/null; then
  echo -e "\n## Architecture Decision Records\n" >> "$OUTPUT"
  for f in docs/adr/*.md; do
    [ -f "$f" ] || continue
    fname=$(basename "$f")
    title=$(extract_title "$f")
    echo "- [${title:-$fname}](adr/$fname)" >> "$OUTPUT"
  done
fi

# --- Domain Models ---
if ls docs/domain/*.md &>/dev/null; then
  echo -e "\n## Domain Models\n" >> "$OUTPUT"
  for f in docs/domain/*.md; do
    [ -f "$f" ] || continue
    fname=$(basename "$f")
    title=$(extract_title "$f")
    echo "- [${title:-$fname}](domain/$fname)" >> "$OUTPUT"
  done
fi

# --- Staleness warnings ---
echo -e "\n## Staleness Warnings\n" >> "$OUTPUT"
STALE_COUNT=0
TODAY=$(date +%Y-%m-%d)
# Compute cutoff: 30 days ago (GNU date -d, macOS date -v)
CUTOFF=$(date -d '30 days ago' +%Y-%m-%d 2>/dev/null || date -v-30d +%Y-%m-%d 2>/dev/null || echo "")

for f in docs/current/*.md docs/adr/*.md; do
  [ -f "$f" ] || continue
  verified=$(extract_field "$f" "last_verified")
  fname=$(basename "$f")
  if [ -z "$verified" ]; then
    echo "- ⚠️ $fname: missing last_verified" >> "$OUTPUT"
    STALE_COUNT=$((STALE_COUNT + 1))
  elif [ -n "$CUTOFF" ] && [ "$verified" \< "$CUTOFF" ]; then
    echo "- ⚠️ $fname: last_verified=$verified (>30 days ago)" >> "$OUTPUT"
    STALE_COUNT=$((STALE_COUNT + 1))
  fi
done
if [ $STALE_COUNT -eq 0 ]; then
  echo "_None_" >> "$OUTPUT"
fi

echo "✅ Generated $OUTPUT"
